### ISSUE TITLE
Upload speed

### ISSUE THREAD

**Issue by nicolas-graves** [regen100/lfs-dal#1]
Hi ! Developer of https://github.com/nicolas-graves/lfs-s3 here. 

I find this initiative very interesting because of the sheer options it allows for git large files management. I'm having some issues when trying to use it though, I will put each in a separate issue. 

I'm testing s3 configuration, basically the same that I use in https://github.com/nicolas-graves/lfs-s3 

First, I'm having a very slow upload speed. It probably on OpenDAL's side, which seem to use an http process while I use the AWS SDK on my side, but my upload speed is not better than 30Ko/s (compared to more than 1Mo/s with the AWS SDK).

**Comment by regen100** [comment]
Thanks for your report! I have reproduced the issue as well. The cause was improper use of buffering in the code I wrote.
I have fixed it in #3, please check it out.

**Comment by nicolas-graves** [comment]
Thanks, that was the issue.
