### ISSUE TITLE
EntityTooSmall S3Error

### ISSUE THREAD

**Issue by nicolas-graves** [regen100/lfs-dal#2]
I don't see any entity_size option in https://opendal.apache.org/docs/services/s3 but I can't upload a file that would be OK using the AWS SDK with the same configuration. 
` => S3Error { code: "EntityTooSmall", message: "Your proposed upload is smaller than the minimum allowed object size.", resource: "", request_id: "" }`

Also, if the error has to happen, it would be great if it would happen before trying to upload the file on the client side rather than after trying to upload the file on the server side.

**Comment by regen100** [comment]
This issue should also be resolved in #3.
According to [the OpenDAL documentation](https://opendal.apache.org/docs/rust/opendal/operator_futures/struct.FutureWriter.html#note:~:text=AWS%20S3%20requires%20the%20part%20size%20to%20be%20in%20%5B5MiB%2C%205GiB%5D.), "AWS S3 requires the part size to be in [5MiB, 5GiB]." so I had to set the buffer size appropriately.

**Comment by nicolas-graves** [comment]
Thanks, that was the issue. 
I'm probably going to archive lfs-s3 and redirect to this program, which is much more versatile and not a lot heavier, I'll need to package this for guix before though. Also feel free on your side to take a look, `test.sh` could be useful to quickly test if a change doesn't break things.
