### ISSUE TITLE
Maintenance and follow-up of the project

### ISSUE THREAD

**Issue by nicolas-graves** [regen100/lfs-dal#4]
Hi again, 

As I said, I'm pretty satisfied by the project and I think it's worth recommending it further, and migrating to it. Before recommending it instead of my own project, after the brief experience I had with other LFS custom agents, I know that they tend to be loosely maintained. I want to know if you indeed intend to support it for some time.

I'll probably keep my project open because of a contribution that adds support for CDN download speedup, which doesn't seem to be possible yet in yours, but will probably add a section to invite users to migrate there.

WDYT?

**Comment by regen100** [comment]
Thank you for your recommendation.
My initial motivation for this project stems from personal interest, but I also plan to use it for my work. So, I can allocate more time to this project than just a hobby project. However, I do not intend to add any more complex features, so the main task will be minor maintenance.
