### ISSUE TITLE
Build of lfs-dal-0.1.1 fails with `error: could not compile `time` (lib) due to 1 previous error`

### ISSUE THREAD

**Issue by sunaemon** [regen100/lfs-dal#8]
## Problem Description
The build of lfs-dal-0.1.1 is failing with Rust 1.80 due to an issue in the `time` crate (https://github.com/time-rs/time/issues/696). This problem occurs when installing via Homebrew:

```
$ brew install lfs-dal
...
==> Installing regen100/lfs-dal/lfs-dal
==> cargo install
Last 15 lines from /Users/sunaemon/Library/Logs/Homebrew/lfs-dal/01.cargo:
   |
help: consider giving `items` an explicit type, where the placeholders `_` are specified
   |
83 |     let items: Box<_> = format_items
   |              ++++++++

   Compiling httpdate v1.0.3
   Compiling spin v0.5.2
   Compiling serde_json v1.0.108
   Compiling unicode-bidi v0.3.14
For more information about this error, try `rustc --explain E0282`.
error: could not compile `time` (lib) due to 1 previous error
warning: build failed, waiting for other jobs to finish...
error: failed to compile `lfs-dal v0.1.1 (/private/tmp/lfs-dal-20240824-44206-bncx6j/lfs-dal-0.1.1)`, intermediate artifacts can be found at `/private/tmp/lfs-dal-20240824-44206-bncx6j/lfs-dal-0.1.1/target`.
To reuse those artifacts with a future compilation, set the environment variable `CARGO_TARGET_DIR` to that path.
```

## Current Status
- The issue in the `time` package has been resolved in its latest version.
- A fix for `lfs-dal` has been merged in https://github.com/regen100/lfs-dal/pull/7.
- However, a new release incorporating this fix has not been published yet.

## Request
Could you please release the latest HEAD version to resolve this issue?

## Workaround
In the meantime, users can install the program using one of the following methods:
1. `cargo install lfs-dal`
2. `brew install --HEAD lfs-dal`

## Additional Information
- Rust version: 1.80
- lfs-dal version: 0.1.1
- Installation method: Homebrew
- OS: macOS 14.4.1
- Hardware: Apple M3 Max

Thank you for your attention to this matter.

**Comment by regen100** [comment]
Fixed by https://github.com/regen100/homebrew-lfs-dal/commit/a39b1fb7f7723c43d50153c3df549efa99dafb0c

**Comment by sunaemon** [comment]
Thanks for fix!
